// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFreePort() {
  return window['go']['main']['App']['GetFreePort']();
}

export function GetMacAcStatus() {
  return window['go']['main']['App']['GetMacAcStatus']();
}

export function GetSecret() {
  return window['go']['main']['App']['GetSecret']();
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function IsMac() {
  return window['go']['main']['App']['IsMac']();
}

export function IsUnifiedDelay() {
  return window['go']['main']['App']['IsUnifiedDelay']();
}

export function OpenConfigDirectory() {
  return window['go']['main']['App']['OpenConfigDirectory']();
}

export function SetMacAc(arg1) {
  return window['go']['main']['App']['SetMacAc'](arg1);
}
