// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportConfig():Promise<string>;

export function ExportCrawl():Promise<string>;

export function GetClipboard():Promise<string>;

export function GetFreePort():Promise<string>;

export function GetMacAcStatus():Promise<string>;

export function GetSecret():Promise<string>;

export function ImportConfig():Promise<string>;

export function IsAdmin():Promise<string>;

export function IsMac():Promise<string>;

export function IsNeedUpdate():Promise<string>;

export function IsUnifiedDelay():Promise<string>;

export function OpenConfigDirectory():Promise<void>;

export function SetMacAc(arg1:string):Promise<string>;

export function SfQuit():Promise<void>;
