// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function ExportCrawl() {
  return window['go']['main']['App']['ExportCrawl']();
}

export function GetClipboard() {
  return window['go']['main']['App']['GetClipboard']();
}

export function GetFreePort() {
  return window['go']['main']['App']['GetFreePort']();
}

export function GetMacAcStatus() {
  return window['go']['main']['App']['GetMacAcStatus']();
}

export function GetSecret() {
  return window['go']['main']['App']['GetSecret']();
}

export function ImportConfig() {
  return window['go']['main']['App']['ImportConfig']();
}

export function IsAdmin() {
  return window['go']['main']['App']['IsAdmin']();
}

export function IsMac() {
  return window['go']['main']['App']['IsMac']();
}

export function IsNeedUpdate() {
  return window['go']['main']['App']['IsNeedUpdate']();
}

export function IsUnifiedDelay() {
  return window['go']['main']['App']['IsUnifiedDelay']();
}

export function OpenConfigDirectory() {
  return window['go']['main']['App']['OpenConfigDirectory']();
}

export function SetMacAc(arg1) {
  return window['go']['main']['App']['SetMacAc'](arg1);
}

export function SfQuit() {
  return window['go']['main']['App']['SfQuit']();
}
