name: Build Linux App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64,arm64 ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install Frontend Dependencies
        run: |
          npm install

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install Backend Dependencies
        shell: pwsh
        run: |
          cd src-go
          go mod tidy

      - name: Get Latest Geo
        run: |
          wget -O src-go/internal/em/geoip.metadb https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.metadb
          wget -O src-go/internal/em/GeoSite.dat https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
          wget -O src-go/internal/em/GeoLite2-ASN.mmdb https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb

      - name: Get Tag Version
        run: |
          git fetch --tags
          VERSION=$(git describe --tags --abbrev=0)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Backend for ${{ matrix.arch }}
        shell: pwsh
        env:
          GOARCH: ${{ matrix.arch }}
        run: |
          cd src-go
          go build -tags=with_gvisor -trimpath -ldflags "-s -w -X github.com/snakem982/pandora-box/api.Version=${VERSION}" -o px

      - name: Build Frontend for ${{ matrix.arch }}
        shell: pwsh
        run: |
          $arch = "${{ matrix.arch }}"
          if ($arch -eq "amd64") {
            $arch = "x64"
          }
          Write-Host "Using arch: $arch"
          npm run make -- --arch=$arch


      - name: Compress Executable
        shell: pwsh
        run: |
          $arch = "${{ matrix.arch }}"
          if ($arch -eq "amd64") {
            $arch = "x64"
          }
          Compress-Archive -Path out\make\deb\$arch\* -DestinationPath "linux-${{ matrix.arch }}-deb.zip"
          Compress-Archive -Path out\make\rpm\$arch\* -DestinationPath "linux-${{ matrix.arch }}-rpm.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${VERSION}
          name: ${VERSION}
          draft: false
          prerelease: false
          files: |
            linux-${{ matrix.arch }}-deb.zip
            linux-${{ matrix.arch }}-rpm.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}